### ISSUE TITLE
BlockDistance Algorithm problem

### ISSUE THREAD

**Issue by initeasylife** [Simmetrics/simmetrics#22]
I learned Taxicab geometry
But I can't understand the relationship between Taxicab geometry and BlockDistance Algorithm.

    public float distance(Multiset<T> a, Multiset<T> b) {

		float distance = 0;

		for (T token : union(a, b).elementSet()) {
			float frequencyInA = a.count(token);
			float frequencyInB = b.count(token);

			distance += abs(frequencyInA - frequencyInB);
		}
		return distance;
	}
The same problem also exists in EdclideanDistance Algorithm

**Comment by mpkorstanje** [comment]
The multi set is a collection c = {(n1, c1), (n2, c2), (n2, c2), ..} where n_ is the name of the element and c_ its occurrence.  Any vector in integer space v = {c1, c2, c3, ...} can be transformed into a multi set by transforming the using the transformation f(c_n) -> (n, |c|). E.g. v = {42, 11, 1008} becomes c = {("one", 42), ("two", 11), ("three", 1008)}. 

Using a multi set rather then a a vector is done because tokening a string and storing the results as vector requires a maintaining a mapping from each token to the index in the vector. That mapping and the vector together also are a multiset.

Other then this the implementation a fairly direct mapping of the formula:

  ![math](https://wikimedia.org/api/rest_v1/media/math/render/svg/02436c34fc9562eb170e2e2cfddbb3303075b28e)

The same reasoning applies to EuclideanDistance.

**Comment by initeasylife** [comment]
thanks 
I have another question
What't different between BlockDistance and EuclideanDistance?
Under what circumstances can I use the Block or Euclidean?

**Comment by mpkorstanje** [comment]
For those question you best consult the relevant Wikipedia articles, the proper stackoverflow site or your tutors. Which metric works best depends on your problem domain and which properties you care about. I can't answer that question.
